"""add source_metadata column

Revision ID: dc43e80622d2
Revises: dced7d93fb98
Create Date: 2026-05-04 11:43:07.352092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc43e80622d2'
down_revision: Union[str, Sequence[str], None] = 'dced7d93fb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_user_source_type', 'data_sources', ['user_id', 'source_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_source_type', 'data_sources', type_='unique')
    op.drop_column('data_sources', 'source_metadata')
    # ### end Alembic commands ###
