from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import get_current_user
from app.models.user import User
from app.schemas.topic import (
    TopicResponse, TopicListResponse,
    TopicDetailResponse, RefreshTopicsRequest,
    RefreshTopicsResponse, MessageResponse,
)
from app.services.topic_service import (
    get_all_topics, get_topic_by_id,
    get_chunks_for_topic, refresh_topics,
)

router = APIRouter(prefix="/topics", tags=["Topics"])


@router.get("", response_model=TopicListResponse)
async def list_topics(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    List all auto-clustered topics for the current user.
    Topics are generated by clustering all ingested chunks.
    Returns empty list if topics have never been generated.
    Call POST /topics/refresh first to generate them.
    """
    topics = await get_all_topics(db, current_user.id)
    return TopicListResponse(
        topics=[TopicResponse.model_validate(t) for t in topics],
        total=len(topics),
    )


@router.post("/refresh", response_model=RefreshTopicsResponse)
async def refresh_topics_endpoint(
    body: RefreshTopicsRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Re-cluster all ingested chunks into topic groups.

    strategy options:
      "auto"   → LLM for ≤150 chunks, KMeans for more
      "llm"    → Always use LLM (better quality, slower)
      "kmeans" → Always use KMeans (faster, works offline)

    max_topics: how many topic groups to create (3-15 recommended)

    This replaces all existing topics for the user.
    Runs synchronously — takes 10-30 seconds depending on data size.
    """
    if body.strategy not in ("auto", "llm", "kmeans"):
        raise HTTPException(
            status_code=400,
            detail="strategy must be one of: auto, llm, kmeans",
        )

    if not (3 <= body.max_topics <= 20):
        raise HTTPException(
            status_code=400,
            detail="max_topics must be between 3 and 20",
        )

    try:
        result = await refresh_topics(
            db=db,
            user_id=str(current_user.id),
            strategy=body.strategy,
            max_topics=body.max_topics,
        )
        return RefreshTopicsResponse(**result)
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Topic refresh failed: {str(e)}",
        )


@router.post("/refresh/async", response_model=MessageResponse)
async def refresh_topics_async(
    body: RefreshTopicsRequest,
    current_user: User = Depends(get_current_user),
):
    """
    Queue topic refresh as a Celery background task.
    Returns immediately.
    Check GET /topics after ~30 seconds.
    """
    from app.workers.tasks import refresh_topics_for_user

    refresh_topics_for_user.delay(
        user_id=str(current_user.id),
        strategy=body.strategy,
        max_topics=body.max_topics,
    )

    return MessageResponse(
        message=(
            "Pingo is clustering your topics in the background. "
            "Check GET /topics in about 30 seconds."
        )
    )


@router.get("/{topic_id}", response_model=TopicDetailResponse)
async def get_topic_detail(
    topic_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Get full detail for a specific topic including
    all the chunks that belong to it.
    This is what the frontend shows when user taps a topic card.
    """
    topic = await get_topic_by_id(db, topic_id, current_user.id)
    if not topic:
        raise HTTPException(status_code=404, detail="Topic not found")

    chunks = await get_chunks_for_topic(db, topic)

    return TopicDetailResponse(
        id=topic.id,
        name=topic.name,
        summary=topic.summary,
        source_types=topic.source_types or [],
        item_count=topic.item_count,
        last_refreshed_at=topic.last_refreshed_at,
        chunks=chunks,
    )


@router.delete("/{topic_id}", response_model=MessageResponse)
async def delete_topic(
    topic_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Delete a single topic.
    Does not delete the underlying chunks — only the cluster.
    Run /topics/refresh to regenerate all topics.
    """
    topic = await get_topic_by_id(db, topic_id, current_user.id)
    if not topic:
        raise HTTPException(status_code=404, detail="Topic not found")

    await db.delete(topic)
    await db.commit()

    return MessageResponse(
        message=f"Topic '{topic.name}' deleted. Run /topics/refresh to regenerate."
    )
